# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Ane
middle_name: Rahbek
last_name: Vierø
contact_note: >
  You can reach me at: ane.rv@protonmail.com.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  a personal website
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  #Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: maps, geospatial, mobility # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: 🌐 # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://anerv.github.io/ # https://alshedivat.github.io # the base hostname & protocol for your site
baseurl: #/al-folio # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true

max_width: 930px

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: false
serve_schema_org: false
og_image:

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:

google_site_verification:
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: maps etc.
blog_description: blog
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  compress_javascript: false
  exclude: ["robots.txt", "assets/js/search/*.js"]

# -----------------------------------------------------------------------------
# Terser
# -----------------------------------------------------------------------------

terser:
  compress:
    drop_console: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  posts:
    enabled: [year, tags, categories]
    permalinks:
      year: "/blog/:year/"
      tags: "/blog/:type/:name/"
      categories: "/blog/:type/:name/"
  books:
    enabled: [year, tags, categories]

display_tags: ["formatting", "images", "links", "math", "code", "blockquotes"]
display_categories: ["external-services"]

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  last_name: [Vierø]
  first_name: [Ane, R.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters: [latex, smallcaps, superscript]
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_link: Details
  query: "@*"
  group_by: year
  group_order: descending

enable_publication_badges:
  altmetric: true
  dimensions: true
  google_scholar: true
  inspirehep: true

filtered_bibtex_keywords:
  - abbr
  - abstract
  - additional_info
  - altmetric
  - annotation
  - arxiv
  - award
  - award_name
  - bibtex_show
  - blog
  - code
  - google_scholar_id
  - html
  - inspirehep_id
  - pdf
  - poster
  - preview
  - selected
  - slides
  - supp
  - video
  - website

max_author_limit: 3
more_authors_animation_delay: 10
enable_publication_thumbnails: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
    - ".gif"
  output_formats:
    webp: "-quality 85"

lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
enable_video_embedding: false

# -----------------------------------------------------------------------------
# Library versions
# -----------------------------------------------------------------------------

third_party_libraries:
  venobox:
    integrity:
      css: "sha256-ohJEB0/WsBOdBD+gQO/MGfyJSbTUI8OOLbQGdkxD6Cg="
      js: "sha256-LsGXHsHMMmTcz3KqTaWvLv6ome+7pRiic2LPnzTfiSo="
    url:
      css: "https://cdn.jsdelivr.net/npm/venobox@{{version}}/dist/venobox.min.css"
      js: "https://cdn.jsdelivr.net/npm/venobox@{{version}}/dist/venobox.min.js"
    version: "2.1.8"

# -----------------------------------------------------------------------------
# Get external JSON data
# -----------------------------------------------------------------------------

jekyll_get_json:
  - data: resume
    json: assets/json/resume.json

jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
